stages:
  generate_dataset:
    cmd: python src/data_generation/DataSetGeneration.py
    deps:
      - src/data_generation/
      - data/raw/
    params:
      - data_generation 
    outs:
      - data/generated/

  train_model:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/generated/
    params:
      - train
    outs:
      - runs/
